### ISSUE TITLE
Can not customize the background in syntax highlight

### ISSUE THREAD

**Issue by DamnWidget** [facelessuser/sublime-markdown-popups#20]
I am not sure if I am doing something wrong but I am not able to customize the background (or any other property) for syntax highlight.

I am following the documentation [here](http://facelessuser.github.io/sublime-markdown-popups/usage/#pygments) but it does not have any effect in the output. I tried using `#!language $(content)` syntax using triple quote `lang $(content)` syntax and even using `mdpopups.syntax_highlight` but none of them work.

I noticed that the CSS output (enabling the debug is just overriding whatever is in my CSS):
```css
...
.mdpopups .variable.parameter { color: #7587A6; }   
    /* this is defined in my CSS fle */
    .mdpopups .highlight, .mdpopups .inline-highlight {        
            background-color: #3B3B3B;          
    }
    /* end of css file */

.mdpopups hr { background-color: #EEFFFF;  }
.mdpopups .highlight, .mdpopups .inline-highlight { background-color: #1D1D1D;   }
```

I am doing something wrong? or this is a bug?

Thanks.
