### ISSUE TITLE
Adapt highlighted code's font-family to view's font_face.

### ISSUE THREAD

**Issue by deathaxe** [facelessuser/sublime-markdown-popups#28]
I was always wondering why the highlighted code in GitGutter's diff popup looked a bit different from the content in the active view. Today I learned you specify a fixed font in your _default.css_ to be used for all the content.

**I would expect the highlighted code in the popup to use the same font set for the view.**

This is _Roboto Mono Light_ in my case.

From this point I had several ideas how to accomplish this.

My **first** idea was to read the view's `font_face` setting and pass it to jinja which renders the stylesheet before passing it to mdpopups in GitGutter at the moment.

My **second** idea was to use mdpopups' `template_vars`. This way GitGutter could ask mdpopups to provide the `font_face` to the stylesheets as `plugin.font_face`.

```python
    jinja_kwargs = {
        'st_version': sublime.version(),
        'wrapper_class': wrapper_class,
        'use_icons': use_icons,
        'view_font_face': view.settings().get('font_face', 'monospace')
    }

    return mdpopups.show_popup(
        view, content, md=False, css=css, wrapper_class=wrapper_class[1:],
        location=location, max_width=max_width, flags=flags,
        on_navigate=navigate, template_vars=jinja_kwargs)
```

The stylesheet could use `{{plugin.font_face}}` variable to adapt the popup's font-family.

```css
.git-gutter .highlight {
    margin: 0.3rem 0.0rem 0.0rem 0.0rem;
    border-radius: 0.25rem;
    font-family: "{{plugin.font_face}}";
}
```

**Finally** the question raises, why does mdpopups not adapt the view font for highlighted code on its own? The colors and font size are already applied to the popup somehow. So font_face would complete this feature, I think.

What's your opinion about it?

Or am I just failing to see the view font being provided already?

**Comment by facelessuser** [comment]
1. The current released version always uses whatever the user is using in their view even if it makes no sense for code.

2. Only 2 days ago did I start forcing a mono space font: https://github.com/facelessuser/sublime-markdown-popups/commit/93ef966130950e5ae203b311a04cd7413b30de16.  You can see it used to be under a CSS `mdpopups-ui` which isn't created by default.  So you shouldn't have seen monospace font being forced until two days ago.  So if you are playing with the bleeding edge, only two days ago would I expect you would see me forcing a monospace font.  The only reason I am forcing a monospace font is because could always looks better as a monospace font, and Sublime users don't always use monospace because maybe some of them mainly do prose, or they hate decent looking code 🙂 .

3.  People can simply go to `User/mdpopups.css` file specify whatever font they want.  I think this is very reasonable.

    ```
    html {
      --mdpopups-font-mono: hack;
    }
    ```

Thoughts?

**Comment by deathaxe** [comment]
> 1. The current released version always uses whatever the user is using in their view even if it makes no sense for code.

The content's font style in popup doesn't match the view since 3127. With a closer look to that and some totally different fonts being set, it looks like a problem with font-weight being ignored by popups. The font-face seems to match. So I was misled ;-)

ST 3126 and mdpopups 1.13.0 renders the popups exactly the same way as the view. 


> 2. Only 2 days ago did I start forcing a mono space font ...

Saw the monospace thing in the master I pulled yesterday, but didn't investigate how long this rule exists this way.

>  The only reason I am forcing a monospace font is because could always looks better as a monospace font, ...

Don't know which font ST/Windows selects but `monospace` looks terrible on Windows and ST. 

> 3. People can simply go to User/mdpopups.css file specify whatever font they want. 

I actually don't find this as simple.

1. As mdpopups is a dependency I never felt the need to study its comprehensive docs to find out that such a file even exists or which keys it contains to be manipulated and which effects they have. Some are clear some are not. I am hardly aware of the basic settings.
2. There is no link or command like _Preferences: mdpopups stylesheet_ or so.

I am honestly confused by all that stylesheet stuff. Some packages hardcode styles, GitGutter comes with an own one, which can be overridden by one other package (theme) or user to modify things historically.  Now I feel it might be redundant as user could place those rules into User/mdpopups.css, too, but who knows. Even mdpopups came with several files in the past, hard to to learn which rules apply to which plugin and/or element.


But in the end you might be right. It's just another setting in just another file. There are so many out there already. One more or less doesn't count. So was maybe simply a wast of time to think about all of that.

**Comment by facelessuser** [comment]
> it looks like a problem with font-weight being ignored by popups

You mean like boldness?  I don't know about that.  Maybe the font-size is slightly different, I use 1rem for the base font so all other sizes are proportional to that.  I don't play with the weight though.  It is possible between 3126 and 3127 Sublime tweaked some things.

> Don't know which font ST/Windows selects but monospace looks terrible on Windows and ST.

I can play with it a bit.  Maybe I can put some better Window's specific fonts in there as default.  This is subjective, but I'll see what I can do.  Some people won't care and some people will.  Pull requests are always welcome.  I do the best I can.

> I actually don't find this as simple.

I think it is fine.  The way I did `mdpopups`, I can't have menu items.  I shouldn't have had the base folder the same as the module folder `mdpopups/mdpopups`.  This creates a situation where once `mdpopups` is added to path, the plugin folder can no longer be seen.  I should have named it something like `python_mdpopups/mdpopups`. Live and learn.  Anyways.  Old versions also had `mdpopups.css` replace the default css, which is why I also never generated one by default, but moving forward, `mdpopups.css` is just appended and overrides only what you define making it better and easier for people to just add what they want.

Like I said, I generally trying to give a decent default CSS, but I'm going to fall short at times.  I don't know what good default Window's fonts I should use.  Maybe I should be using different font lists for Windows vs other OSes.  Not sure.  I am open to suggestions.

I keep running into themes who aren't happy I ignore their stuff (and some of the stuff they do I don't like).  So I've relaxed things somewhat. So:

1. In general (2.0) I will provide a default that generally avoids defining colors (except for syntax highlighting).  It mainly defines for common elements formatting.
2. Plugins can add to that and/or override certain settings.  Users can complain to plugin authors for their plugin specific choices and/or override them in their user settings.
3. Themes (color schemes) somewhere in that process can inject their styles.  I assume that occurs before mdpopups default.css, but I am not sure. I am leaving it up to users to complain to color scheme authors to fix bad choices in their color schemes.
4. Lastly as mentioned before, `mdpopups.css` is the way users can fix things they don't like if plugins, themes, or even I don't agree with their choices.

Plugins need a way for plugin specific styling.  Themes I think should stick to defining color variables, but they will sometimes inject padding etc. Unfortunately that creates a complex system.  `mdpopups.css` is a way for a user to work around what they don't like.

**Comment by deathaxe** [comment]
**First of all. Thank you VERY MUCH for patiently answering my questions and clarifying thinks for me.** 

I've learned much in the last few days and find mdpopups a very comprehensive and helpful dependency. Really good job.

> You mean like boldness? I don't know about that.

By introducing _DirectWrite_ as default font rendering engine, things have definitively changed since ST 3127. This is nothing you or me can influence - it's something like the missing scaling of some GUI elements in prior builts. Maybe the biggest issue is the lag of _Clear Type_ support of ST on Windows. ST uses Skia graphics engine, which is used in Chrome and Firefox and other popular software, too. All of them are capable of good font rendering on Windows. Maybe this just needs some more work for the Core Devs - even though this might not be such a simple task.

> I can play with it a bit. Maybe I can put some better Window's specific fonts in there as default. This is subjective, but I'll see what I can do. 

Maybe this is just related to the font rendering issue as well. Didn't find the one it uses, too, right now. 

I honestly found the solution to adapt the font to the view best, but you are right. I use monospace fonts only and thus didn't see the drawback for users who don't. So forcing some kind of monospace font for code is necessary.

> Unfortunately that creates a complex system. mdpopups.css is a way for a user to work around what they don't like.

Yes, that's right and it was where I trapped myself somehow, yesterday. :-) With the `default.css` being the only stylesheet you provide, things actually get much simpler to understand.

With your help I think I start understanding the system behind all of that.

**Comment by facelessuser** [comment]
I just played with this on Windows, and yes default is ugly.  I added Consolas to the mix and that seems to fix this for later windows.  Whatever it was picking was blocky and weird.  Some other recent tweaks also made it in as well.

**Comment by deathaxe** [comment]
I found out font-smoothing heavily depends on the background color. A font rendering well on dark background gets much thinner on white background. A font rendering well on white gets blocky and ugly on dark backgrounds. Maybe worth an core issue.

**Comment by facelessuser** [comment]
I don't know, that's probably true too.  What I was seeing seemed font dependent as well.  Either way, it looks better for me (when using default font CSS).

**Comment by tukusejssirs** [comment]
Sorry to necrobump this issue (do you prefer opening a new one instead?), but I recently learnt about `mdpopups.css`.

I too want to use exactly the same font size and family in pop-ups as in the file open in ST. Yes, I can change config in `mdpopups.css`, but now I need to remember to change the font size and/or family in two places: in ST settings and in `mdpopups.css`.

I think that creating a variable to use font size and family currently configured in ST also in `mdpopups` would be awesome. :pray:

Also I noticed that `mdpopups.css` require to use space indentation and double quotes. In general, I can (and do) use tab indentation and single quotes, but `mdpopups.css` failed to load when I did so (tested on Arch Linux and ST 4126). It would be nice to support different styles too. :man_shrugging:

**Comment by facelessuser** [comment]
I'm not aware of any issues related to tabs. Tabs work fine for me.

The string issue may or may not be true, I'll take your word for it though, but if that is an issue, it's a Sublime issue, not mdpopups. If double quotes work better, just use double. That's not a deal breaker as far as I'm concerned.

Font size seems to follow the view size already, at least from my experience. I've never tried to measure exact font size to absolutely determine they are identical, but they always seem "close enough".

I don't see an issue with overriding font style in the CSS. That's the way things were designed, so a user can change anything, fonts included, in the CSS. Duplicating in the settings what can already be done with the user CSS doesn't seem like much of a gain and just more maintenance cost on my end.

**Comment by deathaxe** [comment]
It appears some packages may influence how fonts are rendered. Just printed a plain popup out of curiosity.

```py
Python 3.3>>> import mdpopups
Python 3.3>>> mdpopups.show_popup(view=view, content="This is `Hello World` code!")
```
My normal ST setup renders plain text with a fallback font face. It doesn't however happen with a vanilla ST setup with mdpopups being installed only. Both use Default theme and Mariana color scheme.

Both ST setups run Package Control `four-point-oh` branch with mdpopups installed in _Data/Libs/python3.3_. But that doesn't seem to make a difference.

I am aware of an ST core issue, which causes all "default" CSS settings to get lost if the active color scheme defines a `popup_css` global, but I haven't found any so far.

Maybe that's what tukusejssirs is seeing? Not sure what mdpopups could do to prevent something like that however.

#### Productive ST4 setup with dozens of packages

![grafik](https://user-images.githubusercontent.com/16542113/180595586-3a3d8e93-fe11-48d2-ae54-b0b9829449cf.png)

#### Vanilla ST4 setup

![grafik](https://user-images.githubusercontent.com/16542113/180595767-0c2f965e-67a7-4969-802f-bc993c5efc49.png)

### Console Output

<details>

```css
mdpopups: =====CSS=====
mdpopups: 
html {
  --mdpopups-fg: var(--foreground);
  --mdpopups-link: var(--bluish);
  --mdpopups-font-mono: "JetBrains Mono Light", "Liberation Mono", Menlo, Consolas, Courier, monospace;
  --mdpopups-admon-fg: var(--foreground);
  --mdpopups-admon-info-fg: var(--foreground);
  --mdpopups-admon-error-fg: var(--foreground);
  --mdpopups-admon-warning-fg: var(--foreground);
  --mdpopups-admon-success-fg: var(--foreground);
  --mdpopups-admon-bg: var(--background);
  --mdpopups-admon-info-bg: var(--background);
  --mdpopups-admon-error-bg: var(--background);
  --mdpopups-admon-warning-bg: var(--background);
  --mdpopups-admon-success-bg: var(--background);
  --mdpopups-admon-accent: color(var(--background) blend(var(--foreground) 50%));
  --mdpopups-admon-title-fg:  var(--foreground);
  --mdpopups-admon-info-title-fg:  var(--foreground);
  --mdpopups-admon-error-title-fg:  var(--foreground);
  --mdpopups-admon-warning-title-fg:  var(--foreground);
  --mdpopups-admon-success-title-fg:  var(--foreground);
  --mdpopups-admon-info-accent: color(var(--background) blend(var(--bluish) 50%));
  --mdpopups-admon-error-accent: color(var(--background) blend(var(--redish) 50%));
  --mdpopups-admon-warning-accent: color(var(--background) blend(var(--orangish) 50%));
  --mdpopups-admon-success-accent: color(var(--background) blend(var(--greenish) 50%));
  --mdpopups-kbd-fg: var(--background);
  --mdpopups-kbd-bg: var(--foreground);
}
html.light {
  --mdpopups-bg: color(var(--background) blend(black 95%));
  --mdpopups-hr: color(var(--background) blend(black 85%));
  --mdpopups-kbd-border: color(var(--foreground) blend(white 80%));
  --mdpopups-hl-border: color(var(--background) blend(black 90%));
  --mdpopups-hl-bg: color(var(--background) blend(black 98%));
  background-color: var(--mdpopups-bg);
}
html.dark {
  --mdpopups-bg: color(var(--background) blend(white 95%));
  --mdpopups-hr: color(var(--background) blend(white 85%));
  --mdpopups-kbd-border: color(var(--foreground) blend(black 80%));
  --mdpopups-hl-border: color(var(--background) blend(white 90%));
  --mdpopups-hl-bg: color(var(--background) blend(white 98%));
  background-color: var(--mdpopups-bg);
}

html, body { padding: 0; margin: 0 }
div.mdpopups {
  display: block;
  margin: 0;
  padding: 0;
  font-family: "Source Sans 3 Thin";
  font-size: 1rem;
  line-height: 1.6rem;
  color: var(--mdpopups-fg);
  background-color: var(--mdpopups-bg);
}
.mdpopups a {
  color: var(--mdpopups-link);
}
.mdpopups .highlight,
.mdpopups code,
.mdpopups var,
.mdpopups tt {
  font-family: var(--mdpopups-font-mono);
}
.mdpopups div { display: block; }

.mdpopups h1 { font-size: 1.6rem; }
.mdpopups h2 { font-size: 1.4rem; }
.mdpopups h3 { font-size: 1.3rem; }
.mdpopups h4 { font-size: 1.2rem; }
.mdpopups h5 { font-size: 1.1rem; }
.mdpopups h6 { font-size: 1rem; }
.mdpopups h1, .mdpopups h2, .mdpopups h3, .mdpopups h4, .mdpopups h5, .mdpopups h6 {
  margin-top: 0.8rem;
  margin-bottom: 0.5rem;
}

.mdpopups blockquote { display: block; font-style: italic; }

.mdpopups hr {
  display: block;
  border-color: var(--mdpopups-hr);
  border-style: solid;
  border-width: 0 0 1px 0;
  margin-top: 1rem;
  margin-bottom: 1rem;
}

.mdpopups dl { display: block; }
.mdpopups dt {
  display: block;
  font-style: italic;
  font-weight: bold;
  margin-bottom: 0.5rem;
}
.mdpopups dd {
  display: block;
  margin-left: 1.5rem;
  margin-bottom: 0.5rem;
}

.mdpopups pre { display: block; }

.mdpopups blockquote, .mdpopups ol, .mdpopups ul, .mdpopups dl, .mdpopups p {
  padding: 0;
  margin-top: 0;
  margin-bottom: 0.5rem;
  margin-left: 0;
  margin-right: 0;
}
.mdpopups ul, .mdpopups ol { padding-left: 2rem; }

.mdpopups kbd {
  display: inline;
  font-size: 0.9rem;
  padding: 0.05rem 0.25rem;
  border-radius: 0.25rem;
  background-color: var(--mdpopups-kbd-bg);
  color: var(--mdpopups-kbd-fg);
  border: 1px solid var(--mdpopups-kbd-border);
}

.mdpopups .admonition {
  display: block;
  padding: 0 0.5rem 0.5rem 0.5rem;
  border-radius: 0.25rem;
  margin-bottom: 0.5rem;
  background-color: var(--mdpopups-admon-bg);
  color: var(--mdpopups-admon-fg);
  border: 1px solid var(--mdpopups-admon-accent);
}
.mdpopups .admonition-title {
  font-weight: 600;
  font-size: 1.1rem;
  margin: 0 -0.5rem 0.5rem -0.5rem;
  padding: 0.1rem 0.5rem 0.1rem 0.5rem;
  border-top-left-radius: 0.25rem;
  border-top-right-radius: 0.25rem;
  color:  var(--mdpopups-admon-title-fg);
  background-color: var(--mdpopups-admon-accent);
}

.mdpopups .admonition.panel-success .admonition-title {
  color: var(--mdpopups-admon-success-title-fg);
  background-color: var(--mdpopups-admon-success-accent);
}
.mdpopups .admonition.panel-success {
  color:  var(--mdpopups-admon-success-fg);
  background-color: var(--mdpopups-admon-success-bg);
  border-color: var(--mdpopups-admon-success-accent);
}
.mdpopups .admonition.panel-warning .admonition-title {
  color: var(--mdpopups-admon-warning-title-fg);
  background-color: var(--mdpopups-admon-warning-accent);
}
.mdpopups .admonition.panel-warning {
  color:  var(--mdpopups-admon-warning-fg);
  background-color: var(--mdpopups-admon-warning-bg);
  border-color: var(--mdpopups-admon-warning-accent);
}
.mdpopups .admonition.panel-error .admonition-title {
  color: var(--mdpopups-admon-error-title-fg);
  background-color: var(--mdpopups-admon-error-accent);
}
.mdpopups .admonition.panel-error {
  color:  var(--mdpopups-admon-error-fg);
  background-color: var(--mdpopups-admon-error-bg);
  border-color: var(--mdpopups-admon-error-accent);
}
.mdpopups .admonition.panel-info .admonition-title {
  color: var(--mdpopups-admon-info-title-fg);
  background-color: var(--mdpopups-admon-info-accent);
}
.mdpopups .admonition.panel-info {
  color:  var(--mdpopups-admon-info-fg);
  background-color: var(--mdpopups-admon-info-bg);
  border-color: var(--mdpopups-admon-info-accent);
}
.mdpopups .highlight {
  border: 1px solid var(--mdpopups-hl-border);
  border-radius: 0.25rem;
  font-size: 0.9rem;
  background-color: var(--mdpopups-hl-bg);
}
.mdpopups div.highlight,
.mdpopups pre.highlight {
  padding: 0.5rem;
  margin-bottom: 0.5rem;
  font-size: 1rem;
}
.mdpopups code.highlight {
  padding: 0.05rem 0.25rem;
}

mdpopups: =====HTML OUTPUT=====
mdpopups: 
<p>This is <code class="highlight"><span style="color: #d8dee9;">Hello World</span></code> code!</p>
```

</details>
