### ISSUE TITLE
The priority of color scheme CSS prevents consistent styling via color schemes

### ISSUE THREAD

**Issue by jwortmann** [facelessuser/sublime-markdown-popups#70]
The [ST documentation](https://www.sublimetext.com/docs/3/minihtml.html#best_practices) suggests to allow color scheme authors to tweak the look of minihtml popups. With the currently used CSS loading priority (Sublime CSS/color scheme CSS -> MdPopups default CSS -> plugin CSS -> user CSS) it is not possible to style certain html elements/classes from the color scheme, if there already exists a corresponding rule in MdPopups' default CSS or is defined by the plugin. I would like to define a customized `popup_css` style for a color scheme, that is consistent between plugins which use minihtml popups. For example, if I have defined the following CSS as my MdPopups' user CSS:
<details><summary>CSS</summary>
<p>

```css
html {
    margin: 0;
    padding: 0;
    background-color: color(var(--background) blend(var(--foreground) 95%));
    border: 1px solid color(var(--foreground) blend(var(--background) 40%));
}

body {
    margin: 0;
    padding: 0.3rem;
    font-size: 0.9rem;
    color: color(var(--foreground));
}

.error, .deleted {
    color: color(var(--redish));
}

.success, .inserted {
    color: color(var(--greenish));
}

.warning, .modified {
    color: color(var(--orangish));
}

a {
    color: color(var(--bluish));
}

p {
    margin-top: 0.3rem;
    margin-bottom: 0.3rem;
    font-size: 0.9rem;
}

pre {
    display: block;
    padding: 0.3rem;
    font-size: 0.9rem;
    background-color: color(var(--background) blend(var(--foreground) 85%));
    border: 1px solid color(var(--foreground) blend(var(--background) 40%));
    border-radius: 3px;
}

code, .mdpopups code.highlight {
    padding-top: 0;
    padding-bottom: 0;
    background-color: color(var(--background) blend(var(--foreground) 85%));
}

h1, .mdpopups h1 {
    font-size: 1.1rem;
    margin-top: 0.3rem;
    margin-bottom: 0.3rem;
}

h2, h3, h4, h5, h6, .mdpopups h2, .mdpopups h3, .mdpopups h4, .mdpopups h5, .mdpopups h6 {
    font-size: 1rem;
    margin-top: 0.3rem;
    margin-bottom: 0.3rem;
}

.lsp_popup div.highlight {
    padding: 0;
}

.lsp_popup div.errors, .lsp_popup div.warnings, .lsp_popup div.info {
    border: 1px solid color(var(--foreground) blend(var(--background) 40%));
    border-radius: 3px;
}

.lsp_popup div.errors pre, .lsp_popup div.warnings pre, .lsp_popup div.info pre {
    background-color: transparent;
    padding: 0;
    border-style: none;
}

.lsp_popup div.errors a, .lsp_popup div.warnings a, .lsp_popup div.info a {
    padding-top: 0.2rem;
    padding-left: 0.2rem;
}
```

</p>
</details>

Result for a popup from the LSP plugin, which uses MdPopups:
![user_css](https://user-images.githubusercontent.com/6579999/63037433-6b50d000-bebf-11e9-8467-a244de97bf4a.png)

Now, if I instead use the same CSS in my color scheme's `popup_css`, it will look like this:
![popup_css](https://user-images.githubusercontent.com/6579999/63037533-8e7b7f80-bebf-11e9-9469-88870e29d541.png)

For example, here I can not remove the padding for `div.highlight` elements (will be overridden by the default CSS) or use a border for LSP's errors/warnings (`border-width: 0` is defined in the [LSP's plugin CSS](https://github.com/tomv564/LSP/blob/master/plugin/core/popups.py) for those). This is very infuriating because MdPopups is particularly popular for plugins that use minihtml popups.

As a reference, this is the corresponding html of that popup and how it will look by default without any user CSS or `popup_css` styles in the color scheme:
```html
mdpopups: =====HTML OUTPUT=====
mdpopups:
<div class='warnings'><pre>Variable "a" masks variable in parent scope</pre><a href='code-actions'>Code Actions</a></div><div class="highlight"><pre><span style="color: #dddddd;">INTEGER</span><br></pre></div><p><a href='definition'>Definition</a> | <a href='implementation'>Implemenation</a> | <a href='references'>References</a> | <a href='rename'>Rename</a></p>
```
![default](https://user-images.githubusercontent.com/6579999/63037549-99361480-bebf-11e9-88d5-cf2d102c06a1.png)

Therefore I suggest to rearrange the Sublime CSS/color scheme CSS priority between the plugin CSS and the user CSS, so that color scheme authors could provide consistent styles for popups even from plugins that use MdPopups. Plugins could still enforce their own styles by using the `wrapper_class` option with corresponding CSS style definitions, unless the color scheme targets that plugins' specific `wrapper_class`. And users would still be able to override the styling rules just for MdPopups with their own user CSS, if they don't like the style from the Color Scheme.

The automatically generated CSS for color schemes that don't specify a "popup_css" style consists only of the background and foreground color, the link color, and colors for generic classes `.error`, `.deleted`, `.success`, `.inserted`, `.warning`, `.modified`, which are all derived from the colors defined in the color scheme, see [this comment](https://forum.sublimetext.com/t/dev-build-3118/21270/18) in the Sublime Text forum. None of these selectors interfere with MdPopups' default CSS.

What do you think about this?
